### ISSUE TITLE
Unable to run grunt task connect:livereload

### ISSUE THREAD

**Issue by GooSP** [kwk/docker-registry-frontend#103]
Here is the error: 

```
frontend_1 | Running "connect:livereload" (connect) task
frontend_1 | Warning: Object function createServer() {
frontend_1 |       function app(req, res, next){ app.handle(req, res, next); }
frontend_1 |       merge(app, proto);
frontend_1 |       merge(app, EventEmitter.prototype);
frontend_1 |       app.route = '/';
frontend_1 |       app.stack = [];
frontend_1 |       return app;
frontend_1 | } has no method 'static' Use --force to continue.
frontend_1 |
frontend_1 | Aborted due to warnings.
```

I fixed this by changing the following devDependency in "package.json":
`"grunt-contrib-connect": "^0.11.2",`

to:
`"grunt-contrib-connect": "0.8.0",`

as stated in this [thread](https://github.com/gruntjs/grunt-contrib-connect/issues/161#issuecomment-145079883).

**Comment by kwk** [comment]
This was already addressed with #96 which I merged today. But thank you for reporting @GooSP.
