### ISSUE TITLE
Untag - delete a image

### ISSUE THREAD

**Issue by sunshine69** [kwk/docker-registry-frontend#105]
Hi,

The old version (v1) has a feature that allow to untag an image. And then there is a third party script which will find a hash that is not tagged anything and remove them from the file system.

I would like to have a feature like that to remove/cleanup old docker images hosted in the registry.

Thanks

**Comment by HadesArchitect** [comment]
Really nice-to-have.

**Comment by distributorofpain** [comment]
yes please.  :smile:

**Comment by marcelorodrigo** [comment]
+1 for untag an image

**Comment by kwk** [comment]
Duplicate of #106
