### ISSUE TITLE
Cant see tags within a Repository

### ISSUE THREAD

**Issue by axhm3a** [kwk/docker-registry-frontend#119]
## Expected behavior
- _Click on Repositories overview page onto a Repository to list tags of the repository_
## Actual behavior
- _I got an error "repository name not known to registry: banner-service/10"_
## Steps to reproduce the problem
- _Have a single Tag within a repository_
## Specifications
- Docker daemon: 1.10.3
- OS: centOs 7
- Docker Registry Frontend: d5dd87d
## Additional Infos:

URL that will be requested by Registry Frontend: /v2/banner-service/10/tags/list
I think it should be: /v2/banner-service/tags/list

**Comment by kwk** [comment]
Thank you for opening the bug.

Can you please try to access the page with another clean browser and clear
all cache before? It seems that there are persistent cache issues. To
confirm that you can open the web console and see which files are not
actually being downloaded but taken from the cache. Try to fiddle a bit.
I'm sorry for this inconvenience.

Please report back if it works and if not, let us know what you've tried.
Thank you.

2016-04-12 12:29 GMT+02:00 Daniel Basten notifications@github.com:

**Comment by axhm3a** [comment]
![image](https://cloud.githubusercontent.com/assets/1324394/14459181/bddb840c-00b6-11e6-89e5-82a8c8717860.png)

I do not think that this is a cache issue. 

meanwhile i switched to rev `f287a38` but I am not able to run the self builded container because of `/bin/sh: 1: /root/start-apache.sh: not found` on docker run.

**Comment by axhm3a** [comment]
this is a dublicate of feature request: https://github.com/kwk/docker-registry-frontend/pull/100
