### ISSUE TITLE
v2 doesn't show image details

### ISSUE THREAD

**Issue by juanluisbaptiste** [kwk/docker-registry-frontend#121]
## Expected behavior
- Click on a image name
- See image details (image id, author, etc)
## Actual behavior

After clicking on any image the details page load empty. This is happening because "/10" is always being appended to the repository details url:

https://registry-ui.xxxxx.com/v2/busybox/10/tags/list

it should be:

https://registry-ui.xxxxx.com/v2/busybox/tags/list
## Steps to reproduce the problem
- Run container
- Click on an image name
- See the empty details and the browser url includes "/10" (page 10 ?)
## Specifications
- [x] Which version of docker (`docker version`) are you running? 1.10.3
- [x] Which operating system do you use? ubuntu 16.04 beta2
- [x] Which version of the docker-registry-frontend are you running? v2 container, pulled on 04-16/17-2016
  - If you have the frontend running already you can find the version at the very bottom on every page.

git version: d5dd87d

**Comment by arthurdk** [comment]
It's an issue related to namespace handling. There a 3 PR currently  ( #100 ,  #104 & #97  ) that needs to be reviewed and merged (they probably need to be rebased on the latest v2 branch)

Temporary solution: try again with an image that has a full namespace like `busybox/test:version` it should just work fine.
- Specify full namespace on your image on build time or using `docker tag`

```
docker tag busybox registry-host:registry-port/busybox/whatever
```

 and then push the newly tagged image.

**Comment by juanluisbaptiste** [comment]
Yes, that works, thanks.

**Comment by rbrownejr** [comment]
Is this something that's going to be addressed?

**Comment by jbehrends** [comment]
This is still an issue and make this project unusable with the latest versions of the registry.
