### ISSUE TITLE
Does not work when the registry is using self-signed certificates

### ISSUE THREAD

**Issue by M0E-lnx** [kwk/docker-registry-frontend#127]
I'm running an API v2 registry and wanted to use this UI for it.

The registry is configured to use self-signed ssl certificates for the TLS setup.  When I fire this frontend app, it does not list the repositories on the registry.  

I'm using these arguments to the docker run command

``` bash
-e ENV_DOCKER_REGISTRY_HOST=172.17.0.11 \
-e ENV_DOCKER_REGISTRY_PORT=5000 \
-e ENV_REGISTRY_USE_SSL=1
```

Is there anything else I need to make this work?  I couldn't find any reference to using this setup on the documentation.

**Comment by kwk** [comment]
First of all, thank you for your comment.

This is a saved reply. There have been numerous questions like yours and I highly recommend that you take a look at the [example-setup](https://github.com/kwk/docker-registry-frontend/tree/v2/example-setup) directory. It contains a `README` on how to set up a registry with a frontend and it contains a ready-to-use `docker-compose.yml` file for you to run.

I sorry but I cannot help with every setup request coming in. If you find out something that wasn't documented well enough, please contribute back and [open a pull request](https://github.com/kwk/docker-registry-frontend/compare) with your changes to the documentation.

Thank you!
