### ISSUE TITLE
GUI is not finding the docker images

### ISSUE THREAD

**Issue by babatundebusari** [kwk/docker-registry-frontend#144]
After running following command

```
docker run -d -e ENV_DOCKER_REGISTRY_HOST=localhost -e ENV_DOCKER_REGISTRY_PORT=5000 --name docker-registry-frontend -p 8080:80 konradkleine/docker-registry-frontend:v2
```

and going to <ip>:8080

browsing repositories does NOT find any docker images

And when i browse <ip>:5000/v2/_catalog i am able to see list of docker images via registry API

Anything i missed?

**Comment by kwk** [comment]
First of all, thank you for your comment.

This is a saved reply. There have been numerous questions like yours and I highly recommend that you take a look at the [example-setup](https://github.com/kwk/docker-registry-frontend/tree/v2/example-setup) directory. It contains a `README` on how to set up a registry with a backend and it contains a ready-to-use `docker-compose.yml` file for you to run.

I sorry but I cannot help with every setup request coming in. If you find out something that wasn't documented well enough, please contribute back and [open a pull request](https://github.com/kwk/docker-registry-frontend/compare) with your changes to the documentation.

Thank you!

**Comment by babatundebusari** [comment]
I get what you saying but seems like one cannot just run your image on an already existing docker registry?

Because if i am able to get to an already existing docker registry by hostname and port and then i add the exact hostname and port and yet your image can't find the docker images/repositories, then i suspect it is fair to say your image does not work with `already existing` docker registry?

Would have been great, because it seems like a simple stuff right? it should see same thing API sees if hostname and port are correct?

P.S. Most people will probably have an already existing registry with several images.

**Comment by coconitro** [comment]
Something must be wrong with your setup, I dropped this container right in and pointed to existing repo and it worked. If I had an issue working from the example setup and working backwards to eliminate any discrepancies is how I'd probably debug.

There is nothing wrong with pointing this UI to an existing repo.

**Comment by babatundebusari** [comment]
@NitroPye 

Can you explain how you built your existing registry and what command you ran to connect the docker-registry-frontend to it?

P.S. Did you also see my part where i metnioned i browsed the url `<ip>:5000/v2/_catalog`  and i see list of my repositories but then i ran the docker-registry-frontend `<ip>:8080`, browsed repositories and it could not see it? and i uses hostname as `<ip>` and port as `5000`. I mean what else am i supposed to do?

**Comment by coconitro** [comment]
Not to sound repetitive but I followed the example-setup and then substituted my registry information for the one in the example-setup.

I've noticed that your command to run it looks like this:

```
ENV_DOCKER_REGISTRY_HOST=localhost
```

`localhost` is a super no-no here I think. `localhost` inside one container is not `localhost` inside another. This may be part of the problem. 

I also utilized docker links to map the frontend to the registry. e.g. https://github.com/kwk/docker-registry-frontend/blob/v2/example-setup/docker-compose.yml#L6

**Comment by babatundebusari** [comment]
@NitroPye 

You are **RIGHT!**
I changed to **ip address** instead of using `localhost` and it worked
Thanks a lot for pointing that out. I think i tried that for another server and it didn't work but now that i retried on a different setup, it now works

Thanks
