### ISSUE TITLE
where is the delete button?

### ISSUE THREAD

**Issue by babatundebusari** [kwk/docker-registry-frontend#145]
i don't seem to see the delete button

Please see screenshot below
![drfv1](https://cloud.githubusercontent.com/assets/6054104/16939078/143d0d02-4d4c-11e6-93cb-7f8a98271c53.PNG)

also can not see the other details like size of images and stuff as seen from screenshots in repo
![drfv2](https://cloud.githubusercontent.com/assets/6054104/16939115/6ff624c6-4d4c-11e6-8a84-19c4d1bd7032.PNG)

**Comment by kwk** [comment]
This is being discussed in #106
