### ISSUE TITLE
apache2 does not start

### ISSUE THREAD

**Issue by PatrickHennig** [kwk/docker-registry-frontend#148]
Hi all, 

after pulling the image and starting it inside a docker-compose file I do get the following "MPM" error:

`frontend_1  | Module auth_kerb disabled.
frontend_1  | To activate the new configuration, you need to run:
frontend_1  |   service apache2 restart
frontend_1  | Module ssl already disabled
frontend_1  | Enabling module rewrite.
frontend_1  | To activate the new configuration, you need to run:
frontend_1  |   service apache2 restart
frontend_1  | Stopping web server: apache2.
frontend_1  | AH00534: apache2: Configuration error: No MPM loaded.
frontend_1  | Action '-D FOREGROUND' failed.
frontend_1  | The Apache error log may have more information.`

My compose file looks like this: 
`frontend:
  image: konradkleine/docker-registry-frontend:v2
  ports:
    - 127.0.0.1:8081:80
  environment:
    ENV_DOCKER_REGISTRY_HOST: backend
    ENV_DOCKER_REGISTRY_PORT: 5000`

Best Regards, 
Patrick

**Comment by kwk** [comment]
First of all, thank you for your comment.

This is a saved reply. There have been numerous questions like yours and I highly recommend that you take a look at the [example-setup](https://github.com/kwk/docker-registry-frontend/tree/v2/example-setup) directory. It contains a `README` on how to set up a registry with a backend and it contains a ready-to-use `docker-compose.yml` file for you to run.

I sorry but I cannot help with every setup request coming in. If you find out something that wasn't documented well enough, please contribute back and [open a pull request](https://github.com/kwk/docker-registry-frontend/compare) with your changes to the documentation.

Thank you!

**Comment by jc21** [comment]
Duplicate of #88
