### ISSUE TITLE
No pushed images are shown

### ISSUE THREAD

**Issue by hubitor** [kwk/docker-registry-frontend#155]
I can access the frontend but no pushed image appears. I can push images to the registry and pull images from it without frontend. I have tried one time with run commands (A) and one time as described in the example (B). The result is the same with different errors.
## Expected behavior

- [x] *Please describe what you tried to do and what you expect the software to act like.*
- I tried the example here.
- To show the pushed image.

## Actual behavior

- [x] *Please describe what happened instead of the expected behavior.*
No image is shown.

A. Errors in log:
`[Thu Nov 17 19:12:44.789422 2016] [proxy:error] [pid 49:tid 139633656547072] (502)Unknown error 502: [client 172.17.0.1:34396] AH01084: pass request body failed to 172.17.0.2:5000 (registry), referer: https://0.0.0.0:8443/repositories/20
[Thu Nov 17 19:12:44.789460 2016] [proxy:error] [pid 49:tid 139633656547072] [client 172.17.0.1:34396] AH00898: Error during SSL Handshake with remote server returned by /v2/_catalog, referer: https://0.0.0.0:8443/repositories/20
[Thu Nov 17 19:12:44.789463 2016] [proxy_http:error] [pid 49:tid 139633656547072] [client 172.17.0.1:34396] AH01097: pass request body failed to 172.17.0.2:5000 (registry) from 172.17.0.1 (), referer: https://0.0.0.0:8443/repositories/20`

B.  Errors in log:
`[Thu Nov 17 18:19:47.625390 2016] [proxy:error] [pid 41:tid 140589580416768] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:5000 (localhost) failed
[Thu Nov 17 18:19:47.625408 2016] [proxy:error] [pid 41:tid 140589580416768] AH00959: ap_proxy_connect_backend disabling worker for (localhost) for 60s
[Thu Nov 17 18:19:47.625413 2016] [proxy_http:error] [pid 41:tid 140589580416768] [client 172.17.0.1:41590] AH01114: HTTP: failed to make connection to backend: localhost, referer: http://localhost:8080/repositories`

## Steps to reproduce the problem

- [x] *Please describe how a developer can reproduce the issue that you faced.
Make sure you include information how you configured or started the registry and the frontend.*

A. Follow the example.

B. 
```
docker run -d --name registry \
         -p 5000:5000 \
         -e SEARCH_BACKEND=sqlalchemy \
         -e STORAGE_PATH=/registry \
         registry

docker run -d --name registry-frontend \
 -e ENV_DOCKER_REGISTRY_HOST=localhost \
 -e ENV_DOCKER_REGISTRY_PORT=5000 \
 -p 8080:80 \
 konradkleine/docker-registry-frontend:v2
```

## Specifications

 - [x] Which version of docker (`docker version`) are you running?
Docker version 1.12.3, build 6b644ec

 - [x] Which operating system do you use?
Linux Mint 18
 - [x] Which version of the docker-registry-frontend are you running?
3ad864b

**Comment by hubitor** [comment]
B works now.

**Comment by Xepe** [comment]
I am getting the same error, how did you fix it ?

**Comment by hubitor** [comment]
@Xepe Sorry I don't remember. What I do remember for docker in general is that I had oft issues due to permissions.
