### ISSUE TITLE
redirect apache logs to docker stdout/stderr

### ISSUE THREAD

**Issue by jgangemi** [kwk/docker-registry-frontend#24]
yesterday i spent quite a bit of time trying to figure out why requests weren't being proxied to the registry properly. i finally figured it out after exposing `/var/log/apache2` as a volume and mounting it in another container to tail the logs.

it would be great if the container could do this automatically so one would just need to run `docker logs` to see the output.

i'd also have no problem with this being controlled via an env variable so it can be toggled on/off.

**Comment by kwk** [comment]
@jgangemi I've fixed the issue in `v2` and `v1-deprecated` branch. Sorry that it took so long.
