### ISSUE TITLE
apache container doesn't restart cleanly

### ISSUE THREAD

**Issue by stackfull** [kwk/docker-registry-frontend#28]
Occasionally, the container won't start again because the `apache2ctl` command at the bottom of `/root/start-apache.sh` bails with the message 

    "httpd (pid 16) already running"

I guess that means it didn't shut down properly during the container 'stop'. Not sure what to suggest - maybe a cleanup check before the `apache2ctl` call.

**Comment by kwk** [comment]
Thank you for reporting this issue @stackfull. Do you start and stop the docker-registry-frontend container or create a fresh one every time? I prefer to use the latter.

**Comment by stackfull** [comment]
The stop and start is a result of the hosting server being rebooted. I guess I could recycle containers in the init.

**Comment by kwk** [comment]
Please comment on the PR #29 if this looks like as if it fixes the issue.

**Comment by kwk** [comment]
Fixed with 43794d31814813858ca724c60a6572fcf2978113
