### ISSUE TITLE
Docker pull advise shows incorrect port on tag detail view

### ISSUE THREAD

**Issue by randeffects** [kwk/docker-registry-frontend#31]
Docker pull advise on the tag detail page shows port 5000 instead of no port.  As I understand the comments in start-apache.sh 80 and 443 are assumed based on the protocol.
I see the following:
`docker pull registry.mydomain.com:5000/library/redis:3.0`
instead of what I expected:
`docker pull registry.mydomain.com/library/redis:3.0`
I have the environment variable `ENV_REGISTRY_PROXY_PORT=443` set in my config file that is passed to the container.

**Comment by kwk** [comment]
Hi @randeffects and thank you for reporting your problem!

The idea is this: if you don't specify `ENV_REGISTRY_PROXY_PORT`, then `ENV_DOCKER_REGISTRY_PORT` is used as the port to your registry. If the port that is finally used is `80` or `443` (one of the default ports), then it is not shown in the `docker pull ...` line on a tags page. 

Now, I don't know you setup well enough to make any assumptions, but if possible, try setting `ENV_DOCKER_REGISTRY_PORT` to `443` on your container and see if the problem persists, okay?

**Comment by randeffects** [comment]
My setup looks like this: (all containers)
![morpheus-docker-registry](https://cloud.githubusercontent.com/assets/78834/7280269/67d52322-e8d6-11e4-8c1f-443e0e028cd7.png)
So if I set `ENV_DOCKER_REGOSTRY_PORT=443` then I won't be able to connect to the registry, correct?

Is it possible change the tag-detail view to also look at `ENV_REGISTRY_PROXY_PORT` and if that is set to `80` or `443` then do the same as if `ENV_DOCKER_REGISTRY_PORT` is set to `80` or `443`?

**Comment by randeffects** [comment]
This seems to be working now, after restarting with the `ENV_REGISTRY_PROXY_PORT=443` set.  I must have had a page cached in my browser or something.

**Comment by kwk** [comment]
@randeffects I'm glad that you could resolve the issue this way and thank you for taking the time to come back and report it here.
