### ISSUE TITLE
Allow deletion of multiple tags/images at the same time

### ISSUE THREAD

**Issue by artem-sidorenko** [kwk/docker-registry-frontend#32]
Right now if you want to delete multiple tags you have to select them one-by-one and confirm the deletion.
So you want to delete >10 tags/images it starts to be a time consuming task, 
it would be great to have check boxes in the lists and delete button somewhere, or something similar

**Comment by kwk** [comment]
Hi @artem-sidorenko and thank you for reporting this enhancement. Can you think of any other batch operations, one might want to make?

**Comment by artem-sidorenko** [comment]
I think the batch deletion of repositories and tags are the both important things, and actually I do not have an idea for further batch operations in the current feature scope

My specific problem are images/tags generated by CI, so I want to cleanup it sometimes manually.

**Comment by florentvaldelievre** [comment]
+1, I have around 500 tags that I need to remove: 
Exemple, I would like to be able to select all the tags that are more than 8 days. Checkboxs like "gmail" for multiple selection whould be amazing

**Comment by kwk** [comment]
@artem-sidorenko @florentvaldelievre I've created a branch `delete_multiple_items` that contains my work on this issue. In addition I've setup the docker hub to not only build the `latest` tag but also `delete_multiple_items`. Once that is available (in about one hour), please try it out. I look forward to hear about your opinion on those changes. Please also read my comments in 97c9ca0. Hopefully the changes can go into master sooner than later.

**Comment by kwk** [comment]
You should now be able to run
```
sudo docker run \
  -d \
  -e ENV_DOCKER_REGISTRY_HOST=ENTER-YOUR-REGISTRY-HOST-HERE \
  -e ENV_DOCKER_REGISTRY_PORT=ENTER-PORT-TO-YOUR-REGISTRY-HOST-HERE \
  -p 8080:80 \
  konradkleine/docker-registry-frontend:delete_multiple_items
```

**Comment by kwk** [comment]
Changes are in master now see PR #39 for more information.

**Comment by artem-sidorenko** [comment]
Many thx! Very cool:) (tested :))

I have a suggestion for a small enhancement of usability, it would be probably a good idea to have a global checkbox on top/bottom for "select all". It doesn't make sense itself as you can delete the entire repository via a button, but if you have 500 tags following flow might be very helpful:
  - select all tags via this global check box
  - unselect tags you want to keep
  - hit "delete tags"

**Comment by kwk** [comment]
Thx for testing. Your idea about the select all button is documented in my commit message. In fact I think about replacing the smart table as well. It sucks in so many ways when used with controllers per row. But this is another topic.

**Comment by artem-sidorenko** [comment]
@kwk right, sry, my fault
To read completely instead of reading cross helps sometimes:)

**Comment by kwk** [comment]
I think this can be closed. Closing.
