### ISSUE TITLE
registry:2.0 API support

### ISSUE THREAD

**Issue by henrysher** [kwk/docker-registry-frontend#33]
i looked up into V2 API, it seems no API for image listing or searching, which means this frontend may not directly work in new V2 API. From the discussion here: https://github.com/docker/distribution/issues/206, we see that registry authors would like us to take notification to figure out "searching" feature.

**Comment by guruvan** [comment]
Interesting issue indeed. I didn't realize this myself about the v2 api - it seems that the general direction there would allow for non-registry entities to provide multi-registry "search" - i.e. aggregate the catalogs, and provide a search API, which can then be updated with push-style webhook notifications.

**Comment by joberget** [comment]
+1 for this!

**Comment by xiaods** [comment]
+1

**Comment by yangtao309** [comment]
+1

**Comment by arthurbarros** [comment]
+1

**Comment by kwk** [comment]
I'll close this issue now. We have v2 browsing and searching support and you can follow these guidelines to get it up and running: 

https://github.com/kwk/docker-registry-frontend/tree/v2/example-setup

You can search the repo but the notifications is a different topic and rather implementation specific.
