### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by xinity** [kwk/docker-registry-frontend#36]
hi,

i've deployed docker-registry-frontend as documented, but search doesn't seem to work, i have those kind of error in my logs:
```
[Sat May 02 13:28:14.333742 2015] [proxy:error] [pid 32:tid 139787428099840] [client 172.17.42.1:38711] AH00898: DNS lookup failure for: http: returned by /v1/search, referer: http://localhost:8787/
```

here how my docker container works:
```
0509177dde48        docker_registryfrontend:latest    "/bin/sh -c $START_S   5 hours ago         Up 5 hours          443/tcp, 0.0.0.0:8787->80/tcp   docker_registryfrontend_1   
047fd208f3cd        registry:0.9.1                    "docker-registry"      5 hours ago         Up 5 hours          0.0.0.0:5000->5000/tcp          docker_registry_1   
```

they are linked together 

if i try a request using wget/curl from the container `0509177dde48` it works:
```
root@0509177dde48:/# wget http://registry:5000/v1/search     
converted 'http://registry:5000/v1/search' (ANSI_X3.4-1968) -> 'http://registry:5000/v1/search' (UTF-8)
--2015-05-02 15:15:06--  http://registry:5000/v1/search
Resolving registry (registry)... 172.17.0.1
Connecting to registry (registry)|172.17.0.1|:5000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 90 [application/json]
Saving to: 'search'

search                                     100%[========================================================================================>]      90  --.-KB/s   in 0s 
```

any clues about why using the webui it doesn't work ?

**Comment by kwk** [comment]
What happens if you execute `wget http://localhost:8787/v1/_ping` or `wget http://localhost:443/v1/_ping`. Those two request should forward directly to `http://registry:5000/v1/search` or `https://registry:5000/v1/search` respectively.

Please let me know how you've started your containers? The docker-registry-frontend won't simply work with implicit linking. Instead it is designed to work with environment variables where you can specify hostnames/ip addresses and ports.

**Comment by xinity** [comment]
hi ,

tried both URL and i have a 502 error (quite the same message as before), i use docker-compose to start.
here is the yml file:
registry:
    image: registry:0.9.1
    ports:
        - "5000:5000"
   environment:
        - SEARCH_BACKEND=sqlalchemy
        - SETTINGS_FLAVOR=local
        - STORAGE_PATH=/registry

registryfrontend:
    #build: docker-registry-frontend
    image: konradkleine/docker-registry-frontend
    links:
        - registry:registry
    ports:
        - "8080:80"
    environment:
        - ENV_DOCKER_REGISTRY_HOST=http://registry
        - ENV_DOCKER_REGISTRY_PORT=5000

any tips maybe ?

**Comment by kwk** [comment]
Hi,
> registryfrontend:
> #build: docker-registry-frontend
> image: konradkleine/docker-registry-frontend
> links:
> - registry:registry
> ports:
> - "8080:80"
> environment:
> - ENV_DOCKER_REGISTRY_HOST=http://registry
> - ENV_DOCKER_REGISTRY_PORT=5000
> 
My first guess: get rid of the links section and the http:// for the host env as it will be added automatically.

**Comment by xinity** [comment]
if i remove the links, then the name registry won't be resolved by the container :(

second guess is a nice tip, i'll try it and let you know

**Comment by kwk** [comment]
Sorry about that. I thought the name registry was resolvable even without the link. I suggest you keep the link and only remove the http://.

**Comment by xinity** [comment]
no worries :) just tried without the "http://" and it works perfectly !

thanks a lot
