### ISSUE TITLE
No repositories being shown

### ISSUE THREAD

**Issue by DanielKerrigan** [kwk/docker-registry-frontend#46]
Hi. I have been unable to get my repositories to appear. I am running the command from a virtual machine and the registry is located on a different server. I suspect that the problem is due to using a corporate network and the docker-registry-frontend not having the right certificates. When I was first setting up Docker, in order to have been able to access the Docker Hub Registry, I had to install a Root CA and a SSL Decryption certificates on to my vm. Additionally, when I start the Docker daemon on the vm, I have to use "docker -d --insecure-registry aa.aaa.aaa.aaa:5000" Is there a way for me to pass these certificates on to docker-registry-frontend? Can I run the container with the insecure-registry option?
Thanks for the help.

**Comment by kwk** [comment]
Hi @DanielKerrigan. Thank you for reporting your issue. You don't need to do anything for the frontend to talk to an "insecure"  (non-SSL secured) registry. I don't know your topology well enough to help you out here. But if possible, try running both, the registry and the frontend container, on the same VM and first try to get the frontend running. Then after you've made sure that the frontend works, try to start the frontend container again and point it to your real registry.

Please, look at the [Usage](https://github.com/kwk/docker-registry-frontend#usage) parameters and let me know how you started your frontend and registry container and on which IPs both are running.

Good luck!

**Comment by DanielKerrigan** [comment]
Hi, thanks for the reply. I think it was due to an issue with how the private registry was configured. That is in the process of being fixed. I will update you when I am able to check.

**Comment by DanielKerrigan** [comment]
Hi @kwk it's working now! There was a problem with the registry search configuration. Once that was fixed, it worked fine.
