### ISSUE TITLE
List repositories inside a Docker Registry v2

### ISSUE THREAD

**Issue by kwk** [kwk/docker-registry-frontend#47]
The frontend shows a list of all images inside a Docker Registry v2.

**Comment by kikicarbonell** [comment]
:+1: I need it

**Comment by kwk** [comment]
This could be a great additional resource for listing repos: https://github.com/docker/distribution/blob/master/docs/spec/api.md#listing-repositories

**Comment by binhex** [comment]
+1

**Comment by n3r0-ch** [comment]
+1

**Comment by kwk** [comment]
It works already
