### ISSUE TITLE
List tags inside a Docker Registry v2

### ISSUE THREAD

**Issue by kwk** [kwk/docker-registry-frontend#48]
The frontend shall list images inside a repository stored in a Docker Registry v2.

**Comment by kikicarbonell** [comment]
:+1: I need it

**Comment by catuss-a** [comment]
+1, Does it actually work ? I can't make this ui work and I'm using the registry:2 image

**Comment by kwk** [comment]
@catuss-a This is a **planned** feature, so it is not working right now.

**Comment by catuss-a** [comment]
@kwk Yeah I figured it out on another issue, thanks for the feedback!

**Comment by so0k** [comment]
`distribution/registry:master` has an `/v2/_catalog` end point returning a json list of all repositories.

https://github.com/docker/distribution/blob/master/docs/spec/api.md#listing-repositories

**Comment by kwk** [comment]
@so0k Yes, I know it has this but thank you for coming here and posting.

**Comment by samhe** [comment]
+1

**Comment by alexandarp** [comment]
+1

**Comment by binhex** [comment]
+1

**Comment by shabutora** [comment]
+1

**Comment by loveai88** [comment]
+1

**Comment by goern** [comment]
@kwk could you outline what needs to be done to make d-r-f v2 aware?

**Comment by kwk** [comment]
@goern We were using v1 in production for a long time and so I could only spend my time on v1. Now that v2 is here to stay, and so many people are demanding support for it I can finally confirm that I'm working on support for v2 **actively**. So rather than sketching out the details what needs to be done, expect something in the near future.

**Comment by goern** [comment]
even better :) thx for that!

**Comment by vivekjuneja** [comment]
Looking forward to the v2 update !

**Comment by larrycai** [comment]
+1

**Comment by kwk** [comment]
See ef70220d0b79d4d3382718b0c6fb0725ee9b5f83 for a basic implementation. More to come

**Comment by Herrad** [comment]
Is the fact that this has yet to be implemented the reason why I'm getting redirected to the homepage whenever I click on a repository at the moment?

**Comment by kwk** [comment]
@Herrad No, but you should take a look at the example_setup folder to see a basic setup if you have any troubles. Also, notice that currently the only scheme supported is the one of `namespace/repo` while just `repo`is not supported ATM.

**Comment by Herrad** [comment]
That sounds like my problem. Thanks a lot for getting back to me.

**Comment by n3r0-ch** [comment]
+1

**Comment by pmccarren** [comment]
+1

**Comment by ttsz** [comment]
+1

**Comment by kwk** [comment]
By now we can list images inside a V2 registry. We don't support images without a namespace yet, but there's a PR for this if I'm not mistaken.
