### ISSUE TITLE
Disk Space & Remove unused orphan layers

### ISSUE THREAD

**Issue by mahesh3267** [kwk/docker-registry-frontend#49]
Hi , 

We are using "docker-registry-frontend" feel very happy the kind of performence and with UI. 

it willbe more useful if we add docker images stats to the webui, like number of images number, used & unsued orphan layer images with disk size.

also it will be very useful, if we place remove button to clean unused orphan layers from webui.
As myself using script to perform this clean up process manually. 

Let me know if you need any more information. Thank you.

**Comment by kwk** [comment]
Hi @mahesh3267! Thank you for reporting your issue. It nice to hear some positive feedback. So thanks.

The frontend shows almost everything that is exposed by the Docker Registry API v1. The things you refer to are storage dependent. For instance, if you host your registry on Amazon, the frontend would need to access Amazon to find out about orphan images.

I'm sorry, but actual removal of images from your hard drive needs to be done manually as I described at [stackoverflow](http://stackoverflow.com/questions/25436742/deleting-images-from-a-private-docker-registry/25551160#25551160). To build it right into the docker frontend would mean that it knows about the actual storage backend of the registry. Alternatively, one could open a feature request (issue) on the docker registry side to create a Docker Registry API endpoint that forwards request to a custom callback or script that takes care of actually removing images. Personally I vote against this as deletion of orphan images can be complicated especially during push-phase when layers are pushed to which no image refers via a tag. Technically they are orphans but and would have to be deleted but it is not what you want.

Sorry for this long response.

Please, let me know if you object or if this issue can be closed.

**Comment by kwk** [comment]
@mahesh3267 I'm closing this issue because you didn't respond for half a year and the situation hasn't changed that much. Have you found a solution for your problem meanwhile?
