### ISSUE TITLE
Allow Authentication/Authorization per namespace

### ISSUE THREAD

**Issue by Telmo** [kwk/docker-registry-frontend#51]
Similar to how the Docker hub itself does it it would be a nice addition if only authenticated members would be allowed to edit/remove images/tags from a given namespace.

I've tried to implement this with an LDAP backend but had no luck, as a reference here is the section of the apache configuration

```
	<Location "/test">
		<LimitExcept GET>
		AuthBasicProvider ldap
		AuthType Basic
		AuthName "Registry"
		AuthLDAPURL <ldap-url>
		AuthLDAPBindDN <username>
		AuthLDAPBindPassword <password>
		require valid-user
			require ldap-group <my-lap-group-here>
			require ldap-user testuser
		</LimitExcept>
	</location>

	<Location "/#/repository/test">
		<LimitExcept GET>
		AuthBasicProvider ldap
		AuthType Basic
		AuthName "Registry"
		AuthLDAPURL <ldap-url>
		AuthLDAPBindDN <username>
		AuthLDAPBindPassword <password>
		require valid-user
			require ldap-group <my-cn-here>
			require ldap-user testuser
		</LimitExcept>
	</location>
```

The module `authnz_ldap` was enabled. I was able to required LDAP Auth for the whole docker-registry-ui just no for a specific namespace. I assume is due to the `Location` path hence the `/#/repository/test` and `/test` which may seem as duplication.

**Comment by kwk** [comment]
@Telmo Thank you for reporting your issue here. Unfortunately I'm no LDAP expert and I cannot help you. Also, please note that I recently removed the hash (`#`) symbol from all links maybe this works to your advantage.

**Comment by Telmo** [comment]
@kwk sorry if I wasn't clear, the LDAP section is working. I can requires LDAP auth for the whole registry, I kust seem to be unable to do it in a per namespace bases

**Comment by Exordian** [comment]
everything after "#" isn't sent to the server, so you can't fix that this way. this change has to be in the application code. you may only block API calls to specific namespaces (which may result in an error on the application)

**Comment by kwk** [comment]
@Exordian: Like I said, I've switched from hash bang mode (#) to HTML5 URLs

**Comment by kwk** [comment]
No update since August 10th. Therefore closing this now.
