### ISSUE TITLE
CSS not rendering

### ISSUE THREAD

**Issue by rudijs** [kwk/docker-registry-frontend#53]
Hi,

Not sure why, maybe it's just me, but all of a sudden the css is not rendering at all?

Everything appears to be OK, ie css scripts load, but nothing seems to be computed.

Here's a screencap from Chromium (same on Chrome and FireFox for me here).

Anyone else seen this behavior?

![selection_004](https://cloud.githubusercontent.com/assets/1711940/8267026/b379af80-1781-11e5-8cca-199cbae5010a.png)

**Comment by sprijk** [comment]
+1

Same here!

**Comment by kwk** [comment]
@rudijs @sprijk thank you for reporting your issue. Please let me know which version you're running. See bottom of the page for the corresponding git revision. Do you remember which git revision which worked for you? That would help a lot.

**Comment by so0k** [comment]
it happens on both `konradkleine/docker-registry-frontend:latest` & `konradkleine/docker-registry-frontend:v1` in my case. I did have a registry:2 container it linked to, and no v1, but not sure if that's related to this issue.

**Comment by rudijs** [comment]
@kwk I'm git revision: ff69f40

Sorry I don't have the previously working revision, I'm currently only using this on a vagrant VM and I've destroyed the earlier one.

**Comment by far-blue** [comment]
I'm getting this as well. Git revision ff69f40. Running Safari Version 8.0.6 (10600.6.3) (OS X 10.10.3). I'm seeing this on the console: "Unexpected CSS token: :". It says the issue is on line 1 but, of course, the css is compressed so there is only one line.

**Comment by kuvi-innovations** [comment]
+1

Same here

**Comment by kwk** [comment]
I'm working on it...

**Comment by acaranta** [comment]
+1 sry I bothered you on twitter for an already declared issue ;)

**Comment by kwk** [comment]
@rudijs can you confirm that none of the default bootstrap CSS is loading? I think only the toastr and our custom CSS is loaded but not the bootstrap CSS. A quick build of older revisions shows me the same issue here. Therfore I assume some of the external dependencies like Grunt / Bower / NPM have changed in some way. I'm looking into the build output.

**Comment by rudijs** [comment]
@kwk Here's a screen cap from Chromium just now.

The red arrow points to the styles, where nothing seems to be computed.

This suggests Bootstrap is not bootstrapping?

I'm not a bootstrap user (Foundation or Material Design mostly), so I'm not sure where to look exactly other than the dev tools tab.

If you have other suggestions where to look just let me know and I'll have a dig.

![selection_003](https://cloud.githubusercontent.com/assets/1711940/8302750/897c4b9c-19cb-11e5-84d0-35f1a162c8fb.png)

**Comment by rudijs** [comment]
@kwk Here's a shot of inspecting the 'Repositories' text element

![selection_004](https://cloud.githubusercontent.com/assets/1711940/8302797/db1e8758-19cb-11e5-83ff-c295bfca0423.png)

**Comment by rudijs** [comment]
@kwk CSS is getting http 200 status OK

![selection_005](https://cloud.githubusercontent.com/assets/1711940/8302825/152da3ac-19cc-11e5-92c9-6e62826322f0.png)

**Comment by kwk** [comment]
It looks like the `grunt build` step is kicking bootstrap's CSS out. Maybe it thinks it is unused or it cannot find a proper CDN for it I don't know yet but I'm on it. This behavior is new.

**Comment by kwk** [comment]
I've temporarily fixed the issue and a build should be available in the next hour on the docker hub. Please test the build and report that my change fixed the issue for you as well.

**Comment by kwk** [comment]
Ready to use images are available now from the docker hub. Please pull and re-run your containers and let me know what you find out.

**Comment by sprijk** [comment]
Works, thanks!
Op 25 jun. 2015 13:46 schreef "Konrad Kleine" <notifications@github.com>:

**Comment by rudijs** [comment]
@kwk Thanks Konrad!

**Comment by far-blue** [comment]
LGTM

**Comment by kwk** [comment]
Thank you @rudijs  @sprijk @far-blue @acaranta @so0k @kuvi-innovations for reporting this bug and for testing it for me!

**Comment by acaranta** [comment]
Thx for working on it ;)

**Comment by mohitpujara** [comment]
Hi,

I'm using NGINX proxy as a docker container but for me html, css and javascript is not working. this is the snapshot...
![screen shot 2015-07-08 at 11 32 57 am](https://cloud.githubusercontent.com/assets/7598614/8574565/53d9ea1c-2565-11e5-8f88-042b666fdacc.png)

Anyone getting like this?

**Comment by mvdkleijn** [comment]
This does not appear to be fixed and docker pull says I'm on the latest version...
