### ISSUE TITLE
Unable to load web page (HTML, Javascript, CSS not working)

### ISSUE THREAD

**Issue by mohitpujara** [kwk/docker-registry-frontend#58]
Hi,

I'm using NGINX proxy as a docker container but its not loading web page properly...

![53d9ea1c-2565-11e5-8f88-042b666fdacc](https://cloud.githubusercontent.com/assets/7598614/8574932/50fb9974-2567-11e5-95ea-9a94366b0f55.png)

Anyone getting like this?

**Comment by mohitpujara** [comment]
some random numbers are generated on css and javascript filename. It is not fetching the actual file.. It should find main.css, vendor.css, vendor.js, scripts.js.. not vendor.e6551a2c.css and so on..
![screen shot 2015-07-08 at 3 56 54 pm](https://cloud.githubusercontent.com/assets/7598614/8580743/43a0f15c-258a-11e5-9258-e15679237a5f.png)

**Comment by erwin16** [comment]
me too... +1    seems linked to the change in HTML5 links ...?

**Comment by mohitpujara** [comment]
I think its a problem with regex rule on nginx configuration file. i'm unable to find the proper regex rule which will load all the front end stuff.. Temporary i'm writing separate rules for all the front end folder like styles, scripts .... etc

**Comment by kwk** [comment]
Does it work without NGINX?

**Comment by mohitpujara** [comment]
yep.. without NGINX its working..

**Comment by kwk** [comment]
@mohitpujara I cannot help without knowing the nginx configuration.

**Comment by mohitpujara** [comment]
@kwk This is my nginx configuration...

upstream docker-backend {
server backend:5000;
}

upstream docker-frontend {
server frontend:80;
}

server { 
  server_name $host;

  listen 443 ssl; 
  ssl_certificate /etc/nginx/ssl/server.crt; 
  ssl_certificate_key /etc/nginx/ssl/server.key;
  ssl_ciphers 'AES256+EECDH:AES256+EDH::!EECDH+aRSA+RC4:!RC4:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS';
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_session_cache shared:SSL:10m;
  ssl_stapling on;
  ssl_stapling_verify on;
  ssl_prefer_server_ciphers on;
  add_header Strict-Transport-Security max-age=31536000;
  add_header X-Frame-Options DENY;

  client_max_body_size 0; 

  proxy_set_header Host $host; 
  proxy_set_header X-Real-IP $remote_addr; 
  proxy_set_header Authorization "";

  location / { 
    auth_basic "Docker Registry"; 
    auth_basic_user_file /etc/nginx/auth/registry_passwd; 
    proxy_pass http://docker-backend; 
  }

  location ~ ^/ui(/?)(.*)$ { 
    auth_basic "Docker Registry"; 
    auth_basic_user_file /etc/nginx/auth/registry_passwd; 
    proxy_pass http://docker-frontend/$2$is_args$args; 
  }

  location /v1/_ping { 
    proxy_pass http://docker-backend; 
  }

  location /v1/users { 
    proxy_pass http://docker-backend; 
  }
}

**Comment by kwk** [comment]
This might be related to your `/ui/` prefix. Please try to run your frontend without any prefix and reopen this issue if necessary. There's also #50 that deals with this problem. Anyway, please let us know if removing the `/ui/` prefix works.

**Comment by mohitpujara** [comment]
if i'm not giving any prefix then it will redirect to docker-registry which is root and i want docker-registry to be root otherwise i'm unable to pull and push to the registry. There is already a regex rule for /ui/ but its not working.

**Comment by kwk** [comment]
What if you host the registry and frontend on different domains/vhosts?

**Comment by mohitpujara** [comment]
I'm sorry but its not possible for me.. I have to run all stuff in one domain. I think its just a regex rule problem. i'm not getting the proper regex expression.
