### ISSUE TITLE
Storage S3

### ISSUE THREAD

**Issue by berrywira** [kwk/docker-registry-frontend#60]
Hi There!

How to connect docker-registry-frontend with docker registry storage S3, can I?

**Comment by kwk** [comment]
Hi @berrywira , sure you can do that. To be correct, you must configure your registry to store its data in S3, not the frontend. The flow of data then should look like this:

```
Browser <---> Docker Registry Frontend <---> Docker Registry <---> Storage (Filesystem/S3/...)
```

**Comment by berrywira** [comment]
Actualy my docker registry was connected with storage S3. but when I try Docker registry frontend, any repo/image not visible on docker registry frontend.

**Comment by kwk** [comment]
Have you enabled the search backend in your registry config?

Von meinem iPhone gesendet

**Comment by berrywira** [comment]
No, I see on config registry v2 haven't search backend. do you can help me?

**Comment by kwk** [comment]
v2 is is currently not supported but it is being worked on.

2015-08-25 8:52 GMT+02:00 Berry wirattama <notifications@github.com>:

**Comment by berrywira** [comment]
Thanks,I'll be waiting the feature.
