### ISSUE TITLE
It seems like the app is assuming the registry is on the same host instead of using the ENV variable

### ISSUE THREAD

**Issue by cubfan20** [kwk/docker-registry-frontend#62]
I looked at the net calls going out using Firebug and it seems to be constructing the URL by appending to the root instead of utilizing ENV_DOCKER_REGISTRY_HOST.  Can you confirm this?

**Comment by kwk** [comment]
This might look true from the outside but the calls have to go to the same host as the frontend. Everything that goes to the frontend host's /v1/ suffix will be forwarded to the actual registry. We had this "issue" reported before, so please look through the issues to find out why this needs to be done. 

Here some links:

* https://github.com/kwk/docker-registry-frontend/issues/40#issuecomment-103806823
* https://github.com/kwk/docker-registry-frontend/issues/20#issuecomment-103353724

**Comment by cubfan20** [comment]
Are you fully compatible with v2 yet?  Maybe I misunderstood.

Here is the link it is trying to it and it never returns any repos:
http://docker-gui.cme.in.here.com/v2/_catalog?n=10&last=

**Comment by cubfan20** [comment]
Here are the ENV settings just for reference:

ENV_DOCKER_REGISTRY_HOST=docker.cme.in.here.com
ENV_DOCKER_REGISTRY_PORT=443
ENV_DOCKER_REGISTRY_USE_SSL=1

**Comment by kwk** [comment]
My bad! The v2 branch wasn't supposed to show up on hub.docker.com until it is finished or more polished. Your problem should be fixed with this commit: d447896d5a6c221b11971925aa9adc0bc159e738. I tested the code locally and forgot to change the Apache proxy to forward to `/v2/` rather than to `/v1/`. Please, pull the image again and re-test.

**Comment by cubfan20** [comment]
Retried, and it did not work initially. However I logged into the container and pounded out this line in docker-site.conf:

#ProxyPreserveHost On

After a restart of apache it started working.  Can you make that change permanent?

As an aside, I love what you are doing with the site.  It looks great and is very useful.  Thanks for the good work!

**Comment by kwk** [comment]
Hi @cubfan20, please fork the repo, make the change in `apache-site.conf`
and issue a pull request refering to this issue #62 with a concret
description why this line shall be commented out. A link to the
documentation would be nice. Thank you in advance.

2015-09-16 23:04 GMT+02:00 cubfan20 <notifications@github.com>:
