### ISSUE TITLE
Individual repo link redirects back to home page

### ISSUE THREAD

**Issue by marksullivancrowd** [kwk/docker-registry-frontend#64]
I'm running 179467b with a ssl backed apache proxy to my docker registry with a s3 backend

<img width="651" alt="screen shot 2015-09-24 at 13 34 31" src="https://cloud.githubusercontent.com/assets/546141/10074315/20759140-62c7-11e5-8e47-5bc2072a7f9b.png">

clicking any repo brings me here

<img width="649" alt="screen shot 2015-09-24 at 13 34 57" src="https://cloud.githubusercontent.com/assets/546141/10074333/3a5ff5be-62c7-11e5-930c-3913e8c9db39.png">

docker run -e ENV_DOCKER_REGISTRY_HOST=<my_apache_proxy_here>.com -e ENV_DOCKER_REGISTRY_PORT=443 -e ENV_DOCKER_REGISTRY_USE_SSL=1 -p 8080:80 konradkleine/docker-registry-frontend:v2

below is the sequence
http://192.168.99.100:8080/home
http://192.168.99.100:8080/styles/vendor.56eb312d.css
http://192.168.99.100:8080/scripts/scripts.cf6c71f4.js
http://192.168.99.100:8080/scripts/vendor.07ac7afd.js
http://192.168.99.100:8080/styles/main.d603f28b.css
http://192.168.99.100:8080/fonts/glyphicons-halflings-regular.woff2
http://192.168.99.100:8080/scripts/scripts.cf6c71f4.js
http://192.168.99.100:8080/app-version.json
http://192.168.99.100:8080/registry-host.json
http://192.168.99.100:8080/home.html
http://192.168.99.100:8080/favicon.ico
http://192.168.99.100:8080/v2/_catalog?n=10&last=
http://192.168.99.100:8080/app-mode.json

when i manually go to http://192.168.99.100:8080/repository/php56-fpm it redirects me to http://192.168.99.100:8080/home

**Comment by kwk** [comment]
Thank you for testing but filing bugs agains the v2 branch of this repo is currently not a good idea as it is in early development.

**Comment by faraktingi** [comment]
Hi,

I get the same behaviour. Did you fix it please?

**Comment by kwk** [comment]
@faraktingi please start with the example-setup directory and figure it out from there. Plus I need more info.

**Comment by faraktingi** [comment]
Hi and thanks for reply.
Here is my yml file:

frontend:
  image: konradkleine/docker-registry-frontend:v2
  links:
    - registry:registry
  ports:
- 0.0.0.0:8443:443
  environment:
    ENV_DOCKER_REGISTRY_HOST: 'it01vm002.francelab.fr.ibm.com'
    ENV_DOCKER_REGISTRY_PORT: '5000'
    ENV_USE_SSL: 'yes'
    ENV_DOCKER_REGISTRY_USE_SSL: '1'
  volumes:
  - /usr/local/src/certs/domain.crt:/etc/apache2/server.crt:ro
  - /usr/local/src/certs/domain.key:/etc/apache2/server.key:ro
    registry:
    image: registry:2
    ports:
  - 0.0.0.0:5000:5000
    environment:
    STANDALONE: 'True'
    DISABLE_TOKEN_AUTH: 'True'
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: '/data'
    LOGLEVEL: 'debug'
    volumes:
  - /usr/local/src/registry/data:/data

And here is the output docker-compose log:

Starting registry_registry_1
Recreating registry_frontend_1
Attaching to registry_registry_1, registry_frontend_1
registry_1 | time="2016-01-06T15:33:51Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.5.2 instance.id=39a361c3-5a19-42f0-8291-5f7346554ae4 version=v2.2.1 
registry_1 | time="2016-01-06T15:33:51Z" level=info msg="redis not configured" go.version=go1.5.2 instance.id=39a361c3-5a19-42f0-8291-5f7346554ae4 version=v2.2.1 
registry_1 | time="2016-01-06T15:33:51Z" level=info msg="Starting upload purge in 7m0s" go.version=go1.5.2 instance.id=39a361c3-5a19-42f0-8291-5f7346554ae4 version=v2.2.1 
registry_1 | time="2016-01-06T15:33:51Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.5.2 instance.id=39a361c3-5a19-42f0-8291-5f7346554ae4 version=v2.2.1 
registry_1 | time="2016-01-06T15:33:51Z" level=info msg="listening on [::]:5000" go.version=go1.5.2 instance.id=39a361c3-5a19-42f0-8291-5f7346554ae4 version=v2.2.1 
frontend_1 | Module auth_kerb disabled.
frontend_1 | To activate the new configuration, you need to run:
frontend_1 |   service apache2 restart
frontend_1 | Considering dependency setenvif for ssl:
frontend_1 | Module setenvif already enabled
frontend_1 | Considering dependency mime for ssl:
frontend_1 | Module mime already enabled
frontend_1 | Considering dependency socache_shmcb for ssl:
frontend_1 | Enabling module socache_shmcb.
frontend_1 | Enabling module ssl.
frontend_1 | See /usr/share/doc/apache2/README.Debian.gz on how to configure SSL and create self-signed certificates.
frontend_1 | To activate the new configuration, you need to run:
frontend_1 |   service apache2 restart
frontend_1 | Enabling module rewrite.
frontend_1 | To activate the new configuration, you need to run:
frontend_1 |   service apache2 restart
frontend_1 | Stopping web server: apache2.
frontend_1 | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
frontend_1 | [Wed Jan 06 15:33:51.710367 2016] [ssl:warn] [pid 47:tid 140574038968192] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
frontend_1 | [Wed Jan 06 15:33:51.720421 2016] [ssl:warn] [pid 47:tid 140574038968192] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name

Thanks for helping
