### ISSUE TITLE
apache failed to start

### ISSUE THREAD

**Issue by asdfsx** [kwk/docker-registry-frontend#65]
I'm starting the registry by
```shell
docker run \
  -d \
  -e ENV_DOCKER_REGISTRY_HOST=192.168.2.36 \
  -e ENV_DOCKER_REGISTRY_PORT=5000 \
  --net=host \
  konradkleine/docker-registry-frontend
```
but in docker log alway get following message
```python
Module auth_kerb disabled.
To activate the new configuration, you need to run:
  service apache2 restart
Module ssl already disabled
Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
Stopping web server: apache2.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, 
using 192.168.2.36. Set the 'ServerName' directive globally to suppress this message 
```
I don't know what's wrong with it.

**Comment by markriggins** [comment]
Same here.

**Comment by markriggins** [comment]
I bashed into the container, installed curl, and found that it appears to be working internally,  `curl localhost:80` gave back an html page with javascript.

Apache is running

So the above warning message is just a warning. 

But I haven't found the magic to actually connect to this apache server from outside the docker engine.
Tried  `run -P` and just accepted the given Port -- that still gave : 

    curl localhost:32769
    curl: (7) Failed connect to localhost:32769; Connection refused

Do you need to set up something with the routing tables inside the container?  I'm connecting to other http servers inside containers -- but they all run nginx.

**Comment by kwk** [comment]
Try -p 8080:80 on your run command. That maps the port to the outside. It's all in the README.

**Comment by markriggins** [comment]
That's how I ran it.

**Comment by markriggins** [comment]
I found that the problem was that I was trying to use localhost instead of the IP address of my docker engine.  Using Kitematic, click on settings and then the Ports tab for your container, and you will find clickable links with the right IP address and Port

**Comment by kwk** [comment]
Closing because @markriggins reports in his last comment, that the error was resolved.
