### ISSUE TITLE
Browse repositories home page show no repositories

### ISSUE THREAD

**Issue by markriggins** [kwk/docker-registry-frontend#66]
![image](https://cloud.githubusercontent.com/assets/1269690/10177886/92db9e62-66ca-11e5-9f20-69da0a4ebb62.png)

**Comment by kwk** [comment]
@markriggins Okay, first of all, please be more precise in what you expect, what you actually get and how to reproduce the bug. From the screenshot I see that you're running the v2 frontent. Do you have a registry v2 or v1 (aka 0.9.1) deployed? The frontend you're using hasn't official been released yet and just exists for development. If you have a v1 registry, please try adding a `:v1-deprecated` suffix to your frontend image. I understand that the Docker hub lists the wrong branch, but I don't know how to fix this.

**Comment by markriggins** [comment]
Konrad -- our registry has several images, we're running the latest (we just created the registry a few weeks ago).   I didn't know that trying to run it prior to release.   Our registry is v2. 

I can use raw commands to view its _catalog, and tags/lists -- in other words it seems to be working

    /v2/trove-pyramid/tags/list

    { name: "trove-pyramid",
        tags: [
        "latest",
        "local",
        "prod"
       ]
    }

And thank you by-the-way for working to provide something that Docker should have done!!!

What can I do to help?

**Comment by markriggins** [comment]
I cranked up another container off of 'latest' and bashed into the container, and ran
`apt-get update`
`apt-get install curl`
`curl https://docker.<my-domain>/v2/_catalog`

and it appears to work.

    /v2/_catalog
    {"repositories":["centos6-python2.7-uwsi-pyramid","pyramid-uwsgi-nginx","trove-centos7-base","trove-    pyramid","trove-recommend","ubuntu"]}

So I think things are working w.r.t to the server and network.  I didn't see any errors logged.  Not sure what to do next.

**Comment by markriggins** [comment]
By the way -- this looks clever `/bin/sh -c $START_SCRIPT` -- keeps the run command simple

**Comment by kwk** [comment]
@markriggins  Can you show me exactly how your registry config looks like (maybe the raw yaml) and how you start your frontend container?

Also, please let me know the git version number (find it at the bottom of every page in the frontend).

If you can, please have a look at your browsers console to see if there are any pages that cannot be loaded?

Btw. I suggest you run the frontend in [browse mode](https://github.com/kwk/docker-registry-frontend#browse-mode) for the moment because the mofiying features like tagging or deleting are not yet implemented.

**Comment by markriggins** [comment]
Konrad,

I think we probably need to give you time to finish your project.  From
what I've seen it looks like you're off to a good start.   We're using S3
for the backing store, so we can just `s3cmd ls` for now


Mark

**Comment by bchanan03** [comment]
Hi All,

I have same problem - am using docker registry v2.1.1 and here is the yaml file:
http://pastebin.com/XTjfWYTJ
As my docker registry is new - I was able to push localhost:5000/busybox into it
Also I was able to pull the image - but the UI still shows empty list of images on my repository

Here is how I started docker registry:
/usr/bin/docker run -d -p 5000:5000 -v /home/core/trust_authority/containers//secure-registry/config.yml:/go/src/github.com/docker/distribution/cmd/registry/config.yml -e SEARCH_BACKEND=sqlalchemy  -e SQLALCHEMY_INDEX_DATABASE=sqlite:////tmp/docker-registry.db --name secure-registry registry:2.1.1

Here is how I started docker registry UI v2:
docker run -d  -e ENV_DOCKER_REGISTRY_HOST=localhost -e ENV_DOCKER_REGISTRY_HOST=5000 -p 8080:80 konradkleine/docker-registry-frontend:v2

**Comment by kwk** [comment]
@bchanan03 I have no experience with caching enabled. Can you please use an absolute minimal registry configuration? You might also want to remove the `-d` option on `docker run` from both containers to see anything special.

**Comment by zhanglianx111** [comment]
@kwk 
I also have the same problme.This is my steps.
1. start registy image(v1).
 sudo docker run -d --name registry -p 5000:5000 registry
2. start registry UI(This is git revision: f7ebdfd).
sudo docker run --name frontend  -e ENV_DOCKER_REGISTRY_HOST=127.0.0.1 -e ENV_DOCKER_REGISTRY_PORT=5000 -e ENV_MODE_BROWSE_ONLY=true -p 8080:80 konradkleine/docker-registry-frontend
and frontend container show me:
"Module auth_kerb disabled.
To activate the new configuration, you need to run:
  service apache2 restart
Module ssl already disabled
Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
Stopping web server: apache2.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message".
frontend IP is 172.17.0.2

**Comment by kwk** [comment]
@zhanglianx111 You are running the deprecated v1 registry. So your problem is not the same as above. On the other hand what do you expect? Have you pushed images to the repo to show up?

@bchanan03 What does your browser's console log say?

**Comment by zhanglianx111** [comment]
@kwk 
My registry is v1 and I run tag v1-depreacated,but I have nothing in browser.

``` sh
sudo docker run -e ENV_DOCKER_REGISTRY_HOST=127.0.0.1 -e ENV_DOCKER_REGISTRY_PORT=5000 -p 8080:80 konradkleine/docker-registry-frontend:v1-deprecated
```

``` sh
sudo docker run -d -p 5000:5000 registry:0.9.0
```

I push one image into my registry

``` sh
sudo docker search 127.0.0.1:5000/zlx
NAME      DESCRIPTION   STARS     OFFICIAL   AUTOMATED
zlx/uu
```

**Comment by kwk** [comment]
Please consult https://github.com/kwk/docker-registry-frontend/tree/v2/example-setup to get help on how to setup a registry v2 with the frontend.
