### ISSUE TITLE
Delete repository doesn't delete

### ISSUE THREAD

**Issue by nwind21** [kwk/docker-registry-frontend#67]
The home page shows all my repositories but when I check one for removal and do the dialog, it doesn't get deleted.  /v2/_catalog shows the repository is still there.

I also exec bashed into the container to see if there were any errors and I could not find any logs being created.  docker log <container> doesn't show anything interesting besides really short Apache log.

Clues to debug this?

**Comment by kwk** [comment]
Delete is not yet implemented. The buttons are relicts. Please use browse only mode for now when using v2.
