### ISSUE TITLE
Repository missing when using SSL

### ISSUE THREAD

**Issue by bchanan03** [kwk/docker-registry-frontend#68]
Hi All,

I have started docker registry v2 and docker registry UI
when using without SSL .crt/.key I can see the list of repositories
but when using self signed .crt/.key files - I cannot see the repositories :(

Here is how I started both docker registry and docker registry UI
thanks
Chanan

#!/bin/sh -x

. /home/core/trust_authority/bin/env.sh
. /home/core/trust_authority/bin/utils.sh

docker stop $(docker ps -q)
docker rm $(docker ps -q -a)
#_sleep 5
#sudo rm -rf ${TA_DATA_PATH}/registry1

echo "starting secure-registry"
_sleep 5
docker run \
-d \
-p 5000:5000 \
-v $TA_CONTAINER_PATH/secure-registry/certs.d/secure-registry:/certs:ro \
-v $TA_CONTAINER_PATH/secure-registry/config.yml:/etc/docker/registry/config.yml:ro \
-v $TA_DATA_PATH/registry1:/var/lib/registry \
-e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/server.crt \
-e REGISTRY_HTTP_TLS_KEY=/certs/server.key \
-e SQLALCHEMY_INDEX_DATABASE=sqlite:////tmp/docker-registry.db \
-e SEARCH_BACKEND=sqlalchemy \
-h registry11.saas.lab \
--name registry1 \
registry:2.1.1

echo "starting UI"
_sleep 5
IP=$(docker inspect registry1 | jq '.[0].NetworkSettings.IPAddress'|sed -e 's/\"//g')
docker run \
-d \
-e ENV_DOCKER_REGISTRY_HOST=$IP \
-e ENV_DOCKER_REGISTRY_PORT=5000 \
-e ENV_USE_SSL=yes \
-v $TA_CONTAINER_PATH/secure-registry/certs.d/secure-registry/server.crt:/etc/apache2/server.crt:ro \
-v $TA_CONTAINER_PATH/secure-registry/certs.d/secure-registry/server.key:/etc/apache2/server.key:ro \
-p 8080:80 \
konradkleine/docker-registry-frontend:v2

**Comment by kwk** [comment]
@bchanan03 Please run the frontend without the `-d` option and look at the logs inside the container to figure out what's going on.

**Comment by sshipway** [comment]
Same problem here.  If I run the registry with SSL disabled, it works.  With SSL enabled, it is not found.  This is using a Quovadis certificate, with the intermediate certs included with the registry cert.  My guess is that the Quovadis root is not in your CA and the connection fails?

@bchanan03 - if your cert requires intermediate certs, make sure to append them to the cert you use when starting the registry.

**Comment by sshipway** [comment]
I have tried setting up a java keystore with the Quovadis root CA in it, then linking it in with 

  -v $DIR/truststore:/truststore 
  -e 'JAVA_OPTS=-Djavax.net.ssl.trustStore=/truststore -Djavax.net.ssl.trustStorePassword=pass' 

However this does not seem to work as expected (I'm not a Java expert anyway so may well be doing this wrong)

**Comment by sshipway** [comment]
Here's the log.  This is starting the container, and (from the web interface) trying to view the registry.  There seems to be no useful error messages.

rancher repository # export RPORT=5000
rancher repository # export DOMAIN=rancher.container.auckland.ac.nz
rancher repository # export WPORT=8443
rancher repository # sudo docker run -e ENV_DOCKER_REGISTRY_HOST=$DOMAIN    -e ENV_DOCKER_REGISTRY_PORT=$RPORT    -v $DIR/truststore:/tmp/truststore -e 'JAVA_OPTS=-Djavax.net.ssl.trustStore=/tmp/truststore -Djavax.net.ssl.trustStorePassword=password'   -e ENV_USE_SSL=yes    -v $DIR/certs/$DOMAIN.crt:/etc/apache2/server.crt:ro    -v $DIR/certs/$DOMAIN.key:/etc/apache2/server.key:ro    -p $WPORT:443   konradkleine/docker-registry-frontend:v2
Module auth_kerb disabled.
To activate the new configuration, you need to run:
  service apache2 restart
Considering dependency setenvif for ssl:
Module setenvif already enabled
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Enabling module socache_shmcb.
Enabling module ssl.
See /usr/share/doc/apache2/README.Debian.gz on how to configure SSL and create self-signed certificates.
To activate the new configuration, you need to run:
  service apache2 restart
Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
Stopping web server: apache2.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.29. Set the 'ServerName' directive globally to suppress this message

**Comment by kwk** [comment]
@sshipway What does your browser's console log say?

**Comment by unknownbike** [comment]
I am also getting exactly same error as @sshipway, only the difference is  i am using self signed cert.

**Comment by sshipway** [comment]
@kwk - when I look at the container log, I just get the lines in my previous post, nothing helpful.

From what @unknownbike says, I strongly suspect this problem is down to registry server certificate validation problems - if the frontend is validating the cert, then self-signed certs will not validate.  We've had a number of issues in the past with our Quovadis certs as well since their root CA is not in all of the supplied default CA stores.

**Comment by kwk** [comment]
@sshipway unless you post your browsers console log when making a request I cannot help you.

**Comment by sshipway** [comment]
As I mentioned a couple of weeks ago, the logs say:

Module auth_kerb disabled.
To activate the new configuration, you need to run:
  service apache2 restart
Considering dependency setenvif for ssl:
Module setenvif already enabled
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Enabling module socache_shmcb.
Enabling module ssl.
See /usr/share/doc/apache2/README.Debian.gz on how to configure SSL and create self-signed certificates.
To activate the new configuration, you need to run:
  service apache2 restart
Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
[ ok ] Stopping web server: apache2.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.7. Set the 'ServerName' directive globally to suppress this message

This is passing the crt and key using
sudo docker run -e ENV_DOCKER_REGISTRY_HOST=$DOMAIN -e ENV_DOCKER_REGISTRY_PORT=$RPORT -v $DIR/truststore:/tmp/truststore -e 'JAVA_OPTS=-Djavax.net.ssl.trustStore=/tmp/truststore -Djavax.net.ssl.trustStorePassword=password' -e ENV_USE_SSL=yes -v $DIR/certs/$DOMAIN.crt:/etc/apache2/server.crt:ro -v $DIR/certs/$DOMAIN.key:/etc/apache2/server.key:ro -p $WPORT:443 konradkleine/docker-registry-frontend:v2

**Comment by kwk** [comment]
@sshipway that is not the browser but the server's log

**Comment by sshipway** [comment]
Ah - you meant the web browser's javascript console log.  Sorry for the misunderstanding.  Found it, and it looks helpful:

"Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
S@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:3:24902
.query.transformResponse@https://rancher.container.auckland.ac.nz:8443/scripts/scripts.e2fe09fb.js:1:10921
ib@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:4:27864
e@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:4:28482
i@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:5:14638
j/<@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:5:14810
Wb/this.$get</n.prototype.$eval@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:5:22198
Wb/this.$get</n.prototype.$digest@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:5:20703
Wb/this.$get</n.prototype.$apply@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:5:22467
f@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:4:30093
r@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:4:31954
nb/</v.onload@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:5:460
" vendor.9d7c0c79.js:5:9130

"Error: a.config is undefined
b</<.responseError@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:12:27033
i@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:5:14638
j/<@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:5:14810
Wb/this.$get</n.prototype.$eval@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:5:22198
Wb/this.$get</n.prototype.$digest@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:5:20703
Wb/this.$get</n.prototype.$apply@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:5:22467
f@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:4:30093
r@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:4:31954
nb/</v.onload@https://rancher.container.auckland.ac.nz:8443/scripts/vendor.9d7c0c79.js:5:460
"

**Comment by sshipway** [comment]
For clarity in the above:  I am running your UI on rancher.container.auckland.ac.nz:8443 (with HTTPS and a valid certificate) and the test repository is on rancher.container.auckland.ac.nz:5000 (also using SSL)

**Comment by kwk** [comment]
@sshipway Sorry but I cannot support such a scenario because I cannot reproduce it. Please confirm that you can run the registry and the frontend on your localhost first before moving on to external service providers. This should greatly minimize the possible causes for errors.

**Comment by sshipway** [comment]
It runs if I disable the certificates and SSL.  I cannot run it on localhost as Im using a windows workstation with no docker, and have docker in a VM.  The registry works in isolation without issue.

**Comment by kwk** [comment]
Please consult https://github.com/kwk/docker-registry-frontend/tree/v2/example-setup to get help on how to setup a registry v2 with the frontend.

**Comment by sshipway** [comment]
It is now working -- the problem was that I needed to have ENV_DOCKER_REGISTRY_USE_SSL=1 specified; I only had ENV_USE_SSL=yes and had confused the meaning of the two.  This of course explains why everything broke the moment I switched on SSL for the registry...

Looking at the OP script, it looks like @bchanan03 was making the same mistake?

Now I just need to get the registry authentication working.  However that's another story...

**Comment by ghost** [comment]
@sshipway Currently I have the same problem. I am using the registry with a self-signed certificate and I want the registry-frontend to connect to it.
I already set the ENV_DOCKER_REGISTRY_USE_SSL=1 but still the frontend can not connect the registry. I am getting this 404 within the frontend logs:

"GET /v2/_catalog?n=20&last= HTTP/1.1" 404 418 "http://myHostName:8080/repositories/20" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0"

The browser tells me the same.
As this is a self-signed certificate I understand that the frontend must know the CA-certificate. But how can I tell the frontend which CA-cert to use?

**Comment by kwk** [comment]
@sshipway Please consult the [example setup](https://github.com/kwk/docker-registry-frontend/tree/v2/example-setup) as a basis for your own setup and modify it as needed. But start from there to keep it simple.

Regarding your question: The frontend currently doesn't check the registry's certificate. See https://github.com/kwk/docker-registry-frontend/blob/v2/apache-site.conf#L43

**Comment by ghost** [comment]
Ok thanks for your reply. Good to know that the certificate is not checked at all.

My problem was that the frontend container didn't know the target registry's hostname at all. Adding an extra_hosts entry did solve my problem.

**Comment by kwk** [comment]
@broegner ah, I see. So it was a general DNS issue with docker. Thank you for sharing your workaround.
