### ISSUE TITLE
allow DELETE method for removal of images from registry

### ISSUE THREAD

**Issue by stefanleh** [kwk/docker-registry-frontend#69]
In the default configuration i get 405 responses from the apache in the container.
Can you please change the apache configuration to allow DELETE http method?

**Comment by kwk** [comment]
@stefanleh thank you for reporting your problem. Please fork the repo, make the change and open a pull request that references this issue. Thank you in advance.

**Comment by stefanleh** [comment]
Sorry, im not an apache config expert. I just recognized the prob.

**Comment by kwk** [comment]
@stefanleh I'm sorry but I cannot help you then. The HTTP method `DELETE` is not explicitly prohibited anywhere. I think it is less of a problem if you learn a bit of apache config writing than me guessing what your problem is. Consider elaborating on:
- what is version you're using (e.g. git revision)
- what is the use use
- how to reproduce the problem exactly
- what is the expected behavior
- what is observed behavior

**Comment by stefanleh** [comment]
## steps to reproduce
1. `docker run   -d   -e ENV_DOCKER_REGISTRY_HOST=dev-dockerreg   -e ENV_DOCKER_REGISTRY_PORT=5000   -p 9999:80   konradkleine/docker-registry-frontend:v2`
   
   ```
   Digest: sha256:25b72afb2de7b2a11b608d9fff490fcdafb842c7e944697265b05d557f49eccd
   Status: Downloaded newer image for konradkleine/docker-registry-frontend:v2
   494dfd396a207e956caff7a5c3117b32cb688ee377ce9cf3e8f925af4394fe4f
   ```
2. open docker-registry-frontend with browser
3. navigate to image
4. mark image
5. click "delete one tag"
6. check "Check to unlock delete button"
7. click on "delete one item"
8. get redirected docker-registry-frontend to start page

## request in firebug

```
DELETE /v1/repositories/XXX/XXXXX-XXXXX-XXX-XXX/tags/17 HTTP/1.1
Host: host:9999
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Referer: http://host:9999/repository/XXX/XXXXX-XXXXX-XXX-XXX
Cookie: hudson_auto_refresh=true; ACEGI_SECURITY_HASHED_REMEMBER_ME_COOKIE="amVua2luczoxNDQ2NzIyNjUwOTg2OjNlNmFkODM4YjAwYTRlNmQzODE5YTVlZmUyMWRmM2IyNzQ1ZGUzYmJjNDc4MmY3MDliYTEyYzRhOWVkMWE2Yzk="; JSESSIONID.f89646a9=1k331yt942y7e190iar1g7nzd0; screenResolution=1920x1200; JSESSIONID.5814374e=mthokd2yn7mw1v1ytc10w28ga; JSESSIONID.144ed095=yjwf4k7uv2h01mbebasn5pjt5; JSESSIONID=863809EE0019D3CF59B556066D7F325D; JSESSIONID.85faff4a=1xmc4dy1nrit1115c4un4k2449; JSESSIONID.48f47aa5=4ndqiiwf7u441kmp557jnq2gq; JSESSIONID.48bf48cd=17vyl9hsrrvtz1axq8ao637vs; JSESSIONID.80d38f04=1k01g0ipn8jq81bovbazpqr20h; JSESSIONID.838fe7cf=1gvbpblx1ge5g1e1b2egxj8sq7; JSESSIONID.47e67f71=17udd8ub1hcri1b2m41eh8kf7z
Connection: keep-alive
```

## response in firebug

```
HTTP/1.1 405 Method Not Allowed
Date: Thu, 29 Oct 2015 14:28:34 GMT
Server: Apache/2.4.10 (Debian)
Allow: GET,HEAD,POST,OPTIONS
Content-Length: 317
Keep-Alive: timeout=5, max=97
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1
```

**Comment by kwk** [comment]
Hi @stefanleh. Sorry for having caused work on your site but for v2, deletion of images is not yet supported and the buttons are a relic from v1. Use browse only mode. We already had a quite similar issue: #67 .
