### ISSUE TITLE
redirect to home page

### ISSUE THREAD

**Issue by schmel** [kwk/docker-registry-frontend#74]
git revision: bdbe5cb (build from github Dockerfile)
The command docker run -d -e ENV_DOCKER_REGISTRY_HOST=gelios -e ENV_DOCKER_REGISTRY_PORT=5000 -p 8080:80 registry2 just worked for me.

It opens up on the browser well I am see all repository, but all links redirect to home page.

The command docker run registry v2:
docker run -d -p 5000:5000 --restart=always -v /etc/certs:/certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt -e REGISTRY_HTTP_TLS_KEY=/certs/registry.key registry:2

In all hosts  /etc/default/docker:
DOCKER_OPTS="--insecure-registry gelios:5000"

**Comment by kwk** [comment]
Please make sure your repos live under a namespace and not in the global namespace. Reopen if necessary. Also check the example https://github.com/kwk/docker-registry-frontend/tree/v2/example-setup
