### ISSUE TITLE
problem access registry over SSL

### ISSUE THREAD

**Issue by dmasar** [kwk/docker-registry-frontend#78]
Hi,

I start frondend with following command

docker run -i --rm -e ENV_DOCKER_REGISTRY_HOST=reggui.xxdomain.com -e ENV_DOCKER_REGISTRY_PORT=5000 -e ENV_DOCKER_REGISTRY_USE_SSL=1 -p 9090:80 --name reggui -h reggui.xxdomain.com konradkleine/docker-registry-frontend:v2

but frondend does not list any images.
then I see these errors in frondend out:

[Fri Dec 11 15:05:48.573865 2015] [proxy:error] [pid 48:tid 140297187063552](110)Connection timed out: AH00957: HTTPS: attempt to connect to 192.168.xxx.xxx:5000 (reggui.xxxdoamin.com) failed
[Fri Dec 11 15:05:48.573903 2015] [proxy:error] [pid 48:tid 140297187063552] AH00959: ap_proxy_connect_backend disabling worker for (reggui.xxxdoamin.com) for 60s
[Fri Dec 11 15:05:48.573912 2015] [proxy_http:error] [pid 48:tid 140297187063552] [client 192.168.136.74:59072] AH01114: HTTP: failed to make connection to backend: reggui.xxxdoamin.com, referer: http://reggui.xxxdoamin.com:9090/

Registry uses SSL server cert issued by sefsigned custom authority. Is there any config I need to do in frondend container?

Registry is fine accessible over ssl from another hosts.

command to starrt registry

docker run -i --rm -p 5000:5000 \
        -v /home/dmasar/registry/data:/var/lib/registry \
        -v /home/dmasar/registry/certs:/certs \
        -v /home/dmasar/registry/config.yml:/etc/docker/registry/config.yml \
        --name reg registry:2

config.yml
version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /var/lib/registry
http:
    addr: :5000
    headers:
        X-Content-Type-Options: [nosniff]
    tls:
        certificate: /certs/reghost.crt
        key: /certs/reghost.key
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

Thanks a lot.

Daniel.

**Comment by kwk** [comment]
See example-setup folder and start from there.
