### ISSUE TITLE
run issues

### ISSUE THREAD

**Issue by Toplife** [kwk/docker-registry-frontend#79]
did you have meet this case?
when I run docker-compose up
finally show me:
frontend_1 | /bin/sh: 1: /root/start-develop.sh: Permission denied
How to fix it?
thanks

**Comment by kwk** [comment]
@Toplife Which version have you checked out? Please execute `git log -n1` and post the result here.

**Comment by Toplife** [comment]
@kwk 
I have solved this problem. I just pull all images and update docker-compose.yml file.
And run docker-compose up
It`s ok.
Thanks for you response.

**Comment by kwk** [comment]
@Toplife Thanks for getting back here and reporting your issue. I'm closing this now.
