### ISSUE TITLE
No delete buttons?

### ISSUE THREAD

**Issue by cartley** [kwk/docker-registry-frontend#82]
I am probably doing something wrong.... I can browse my registry, but I don't get any delete buttons or fields for manipulating tags. What does that indicate?
file:///lair/cartley/Desktop/nodelete.png

**Comment by coconitro** [comment]
I think if your registry is v2 none of that functionality is implemented yet. 

Also from the README.md:

```
NOTE For now ENV_MODE_BROWSE_ONLY will be overwritten to true.
```

At least thats what I took away from it. I could be wrong.

**Comment by cartley** [comment]
I am using the v2 branch of the the frontend, via the docker container on dockerhub:
    konradkleine/docker-registry-frontend:v2

I started it like this:
$ docker run -d --name docker-registry-frontend  \
 -e ENV_DOCKER_REGISTRY_HOST=myreghost.foo.com \
 -e ENV_DOCKER_REGISTRY_PORT=5000  \
 -e ENV_MODE_BROWSE_ONLY=false  \
 -p 80:80  konradkleine/docker-registry-frontend:v2

And I verify that my registry is v2:
$ docker exec registry registry --version
registry github.com/docker/distribution v2.2.1

**Comment by coconitro** [comment]
Almost same setup here w/ no delete buttons since:

```
NOTE For now ENV_MODE_BROWSE_ONLY will be overwritten to true.
```

**Comment by chenjun3092** [comment]
Please! I have the same problem：“I don't get any delete buttons or fields for manipulating tags.”
I started it like this:
sudo docker run \
  -d \
  -e ENV_DOCKER_REGISTRY_HOST=0.0.0.0 \
  -e ENV_DOCKER_REGISTRY_PORT=5000 \
  -p 9988:80 \
  konradkleine/docker-registry-frontend:v2

and: docker exec registry registry --version
registry github.com/docker/distribution v2.2.1

eg:

![312_20160108_101308](https://cloud.githubusercontent.com/assets/9348676/12188526/28624e8e-b5f1-11e5-89b9-c381334fd64b.JPG)

![312_20160108_101325](https://cloud.githubusercontent.com/assets/9348676/12188531/2cd70cc0-b5f1-11e5-9737-3f3398c14b36.JPG)

**Comment by coconitro** [comment]
> NOTE For now ENV_MODE_BROWSE_ONLY will be overwritten to true.

**Comment by kwk** [comment]
@NitroPye is right. Currently delete buttons are disabled for v2.

**Comment by moenka** [comment]
Would be good to know why they are disabled. The current official docker registry v2 supports deleting images. Why not use the pros of open source when providing open source? Someone else could write the code for the implementation or solve the problem if it's known what blocks this feature.

**Comment by Clashsoft** [comment]
Any updates on this? I installed this specifically for the Delete feature because it is tedious with commands.
