### ISSUE TITLE
https://my_domain/repository/foo/bar/foobar, redirect to home page

### ISSUE THREAD

**Issue by CodeJuan** [kwk/docker-registry-frontend#86]
Hi @kwk 
Thank you for your docker-registry-frontend.

when I click the link of the image(foo/bar/foobar:1.0, the address is https://my_domain/repository/foo/bar/foobar), then it redirect to home page.
git revision: bc7a80b (pull V2)

I read the `app.js`, and I found that the url(https://my_domain/repository/foo/bar/foobar) didn't match the pattern `'/repository/:repositoryUser/:repositoryName'` . 
I thought that the tag of my image is wrong, it should be `user/repo_name`, so I modify the tag to `user/repo_name`
, then it works.

**Comment by stevebannon** [comment]
I'm seeing similar behavior.  I think what is happening is I am clicking on the link for the image and I am getting an error from the registry so it is shooting me back to the homepage.  Here's my process

-build container called webapp
-tag webapp:latest foo.example.com/webapp:latest (foo.example.com is my priv registry)
-push foo.example.com/webapp:latest

This would show up on the frontend in a heading called webapp with a link called webapp under it.

That link just leads me back to the frontpage.

**Comment by kwk** [comment]
Currently we only support the registry/namespace/repo scheme. Please don't use registry/repo.

**Comment by CodeJuan** [comment]
I got it.
Thanks @kwk @stevebannon
