### ISSUE TITLE
Cannot go to the details page of any image

### ISSUE THREAD

**Issue by yorch** [kwk/docker-registry-frontend#89]
I installed it with a Registry v2, it lists all my images, but when I click on an image, it redirects me to the home page, any ideas?

**Comment by coconitro** [comment]
If your images are in the global namespace that will happen. You need to namespace them it seems. 

E.g. yourregistry/image won't work
yourregistry/namespace/image will work

**Comment by kwk** [comment]
@NitroPye, that is correct for now.

**Comment by jiger25783** [comment]
What do you mean by namespacing image?  I am also having same issue
