### ISSUE TITLE
Impossible to delete image from Web interface

### ISSUE THREAD

**Issue by RomanGrekov** [kwk/docker-registry-frontend#90]
I run frontend with next yml file:
registry-frontend:
  restart: never
  image: konradkleine/docker-registry-frontend:v2
  container_name: docker-registry-frontend
  ports:
    - 8443:443
  environment:
    - ENV_DOCKER_REGISTRY_HOST=bla.bla.com
    - ENV_DOCKER_REGISTRY_PORT=443
    - ENV_DOCKER_REGISTRY_USE_SSL=1
    - ENV_USE_SSL=yes
  volumes:
    - /opt/docker-registry/certs/domain.crt:/etc/apache2/server.crt
    - /opt/docker-registry/certs/domain.key:/etc/apache2/server.key

Web interface work fine, but there are no any controls to delete image or repo
![screenshot from 2016-01-28 12 37 48](https://cloud.githubusercontent.com/assets/7127528/12642101/597307e0-c5bc-11e5-9a38-56f1de3d8331.png)

**Comment by kwk** [comment]
Please look at the README. This feature is currently disabled.
