### ISSUE TITLE
problems with registry url

### ISSUE THREAD

**Issue by theresiasnow** [kwk/docker-registry-frontend#91]
We have an apache proxy in front of the docker registry, tried connecting through that using https, tried directly accessing port 5000 (registry port) using http. The java script console shows that the gui tries to access the repo through the application url, not the registry uri.

screenshot from trying running the application from my laptop. Similar when running on the server.

<img width="1586" alt="skarmklipp 2016-01-29 13 19 43" src="https://cloud.githubusercontent.com/assets/817037/12675541/578d93d0-c68b-11e5-9db1-d6e8cde22b99.png">

**Comment by kwk** [comment]
That is correct the GUI of the docker-registry-frontend calls the frontend `/v2` path which is then proxied to the registry by the Apache in the docker-registry-frontend. See https://github.com/kwk/docker-registry-frontend/blob/v2/apache-site.conf#L47 for example. I think I did that to not have CORS issues.
