### ISSUE TITLE
Clicking on repository item redirects to home.

### ISSUE THREAD

**Issue by vkorehov** [kwk/docker-registry-frontend#93]
1) clicking on registry item redirects to home.
2) there are no any modification buttons, i.e. delete repository etc.  after there is at least one item in registry, button just dissapears....

**Comment by kwk** [comment]
@vkorehov Thank you for reporting your issue. 

Please look at the example setup folder for a guide on how to setup your repository. Also, please note that we don't support images without a namespace. Consider creating your images tagged as follows: `my-registry.com/mynamespace/myrepository:mytag`.

This will _not_ work: `my-registry.com/myrepository:mytag`.

Reopen this issue if this doesn't fix your issue and please proivide more information about your installation and setup. But first consult the example setup. I cannot provide support for each indivisual setup.

**Comment by vkorehov** [comment]
hi,
this was not adequately described in any documentation source, I was following steps in example setup folder readme.
And on docker site, this is a sequence of steps, from official docker documentation, as you see it doesn't mention any tags:
docker pull ubuntu && docker tag ubuntu 192.168.2.148:5000/ubuntu
docker push localhost:5000/ubuntu
docker pull localhost:5000/ubuntu

Anyway, GUI must fail in a more adequate way, instead of redirecting to home page and giving no reason, so this issue is valid.

Cheers,

**Comment by kwk** [comment]
> this was not adequately described in any documentation source, I was following steps in example setup folder readme.

Naming images with a namespace is considered best practice.
- https://docs.docker.com/engine/userguide/dockerrepos/#contributing-to-docker-hub
- This section says where to go before you open a bug: https://github.com/kwk/docker-registry-frontend#before-opening-a-bug-report
  - This section has an example of how to tag an image: https://github.com/kwk/docker-registry-frontend/tree/v2/example-setup#usage : `docker tag busybox 0.0.0.0:5000/busybox/busybox`

Not here to argue about this though.

> Anyway, GUI must fail in a more adequate way, instead of redirecting to home page and giving no reason, so this issue is valid.

And a good bug report contains a section about what you do, what you expect, what really happens. Yet your bug report doesn't contain any description about what you expect to happen. Got it?

**Comment by vkorehov** [comment]
sure, im not going to argue about some "trash ui" which is not trash in your opinion.
All i did was:
docker pull ubuntu && docker tag ubuntu 192.168.2.148:5000/ubuntu
docker push localhost:5000/ubuntu
docker pull localhost:5000/ubuntu

after that "Remove selected" button dissapeard, Now, I've deleted registry directory and buttotn didn't reappeared.
this is insane...

**Comment by umairaslamm** [comment]
Hi, as you mentioned it should be used as 
my-registry.com/mynamespace/myrepository:mytag
so I have my images like my-registry:5000/mynamespace/myrepo:tag
but its still not working. I am wondering if it is the colon and the port instead of dot and com which is creating the issue. Any ideas ??

**Comment by umairaslamm** [comment]
I think i have found the bug. The home page makes a request as follows
https://my-registry/registry-host.json
which returns the following response
{"host": "my-registry", "port": 5000}
where as when click on "Browse repositories" button, it makes the following request
https://my-registry/v2/_catalog?n=20&last=
which results in 502 Proxy Error. The UI should append the port returned by "registry-host.json" request
Do you think I should open a new bug for this or not ?

**Comment by fotisp** [comment]
So is this a valid issue or not?

**Comment by kwk** [comment]
@umair-aslam, @fotisp No, that is not a bug. The apache proxies everything beginning with `/v2/` to the correct registry. Have you tried the [example-setup](https://github.com/kwk/docker-registry-frontend/tree/v2/example-setup#example-setup) yet? It should work right out of the box.
