### ISSUE TITLE
Browse Mode is always true

### ISSUE THREAD

**Issue by GerardSoleCa** [kwk/docker-registry-frontend#95]
Hi,

I'm trying to setup this frontend. I've an htpasswd running registry which is working fine. I've setup the frontend configuration as the example but the frontend is always running as browse only.

First time asks for my credentials on the registry and once logged in, the images and tags are listed properly, but I'm unable to manage them (no tag/remove) like in screenshots.

I've seen in chrome's console that frontend is being configured as browse only and I'm unable to change how this works.

Does anyone know what's going on?

Thanks in advanced :)

**Comment by kwk** [comment]
Currently browse mode is always on. We're working on this but don't expect anything to happen anytime soon. There were initial API issues when moving from v1 to v2 of the registry.

https://github.com/kwk/docker-registry-frontend#browse-mode:

> **NOTE** For now `ENV_MODE_BROWSE_ONLY` will be overwritten to `true`.
